<a href="https://colab.research.google.com/github/lowejie/Python/blob/main/HSR_Character_v1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (from opendatasets) (1.6.17)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from opendatasets) (8.1.8)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2025.1.31)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.3.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.11/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->kaggle->opendatasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->kaggle->opendatasets) (3.10)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [9]:
import opendatasets as od
import pandas as pd

Download Honkai Star Rail Character Dataset as of version 1.2

In [10]:
od.download(
    "https://www.kaggle.com/datasets/ridhopandhu/honkai-star-rail-character-data")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: lowejie
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/ridhopandhu/honkai-star-rail-character-data
Downloading honkai-star-rail-character-data.zip to ./honkai-star-rail-character-data

100%|██████████| 3.99k/3.99k [00:00<00:00, 2.37MB/s]

In [15]:
file =('/content/honkai-star-rail-character-data/hsr_character-data.csv')
hsr_df = pd.read_csv(file)

In [16]:
hsr_df.head()

,character,rarity,path,combat_type,wb_b-atk,wb_skill,wb_ult,er_b-atk,er_skill,er_ult,...,hp_40,atk_20a,def_20a,hp_20a,atk_20,def_20,hp_20,atk_1,def_1,hp_1
0,march_7th,4,preservation,ice,30,0,60,20,30,5,...,540,163.56,183.30,338,135.72,152.10,281,69.60,78.0,144
1,dan_heng,4,hunt,wind,30,60,90,20,30,5,...,450,174.84,126.90,282,145.08,105.30,234,74.40,54.0,120
2,himeko,5,erudition,fire,30,60,60,20,10,5,...,535,241.96,139.59,335,200.77,115.83,278,102.96,59.4,143
3,welt,5,nihility,imaginary,30,30,60,20,30,5,...,574,198.53,162.86,360,164.74,135.14,299,84.48,69.3,153
4,kafka,5,nihility,lightning,30,60,60,20,30,5,...,554,217.14,155.10,347,180.18,128.70,288,92.40,66.0,148

Dataset basic information

In [22]:
hsr_df.info

<bound method DataFrame.info of         character  rarity          path combat_type  wb_b-atk  wb_skill  \
0       march_7th       4  preservation         ice        30         0
1        dan_heng       4          hunt        wind        30        60
2          himeko       5     erudition        fire        30        60
3            welt       5      nihility   imaginary        30        30
4           kafka       5      nihility   lightning        30        60
5     silver_wolf       5      nihility     quantum        30        60
6           arlan       4   destruction   lightning        30        60
7            asta       4       harmony        fire        30        30
8           herta       4     erudition         ice        30        30
9          bronya       5       harmony        wind        30         0
10          seele       5          hunt     quantum        30        60
11         serval       4     erudition   lightning        30        60
12         gepard       5  preservation         ice        30        60
13        natasha       4     abundance    physical        30         0
14           pela       4      nihility         ice        30        60
15          clara       5   destruction    physical        30        30
16          sampo       4      nihility        wind        30        30
17           hook       4   destruction        fire        30        60
18           luka       4      nihility    physical        30        60
19        qingque       4     erudition     quantum        30         0
20        tingyun       4       harmony   lightning        30         0
21         luocha       5     abundance   imaginary        30         0
22      jing_yuan       5     erudition   lightning        30        30
23          blade       5   destruction        wind        30         0
24        sushang       4          hunt    physical        30        60
25         yukong       4       harmony   imaginary        30         0
26        yanqing       5          hunt         ice        30        60
27          bailu       5     abundance   lightning        30         0
28  trailblazer_0       5   destruction    physical        30        60
29  trailblazer_1       5  preservation        fire        30         0
30    dan_heng_IL       5   destruction   imaginary        30         0
31           lynx       4     abundance     quantum        30         0
32        fu_xuan       5  preservation     quantum        30         0

    wb_ult  er_b-atk  er_skill  er_ult  ...  hp_40  atk_20a  def_20a  hp_20a  \
0       60        20        30       5  ...    540   163.56   183.30     338
1       90        20        30       5  ...    450   174.84   126.90     282
2       60        20        10       5  ...    535   241.96   139.59     335
3       60        20        30       5  ...    574   198.53   162.86     360
4       60        20        30       5  ...    554   217.14   155.10     347
5       90        20        30       5  ...    535   204.73   147.34     335
6       60        20        30       5  ...    612   191.76   105.75     384
7        0        20         6       5  ...    522   163.56   148.05     327
8       60        20        30       5  ...    486   186.12   126.90     305
9        0        20        30       5  ...    634   186.12   170.61     397
10      90        20        30       5  ...    475   204.73   116.33     298
11      60        20        30       5  ...    468   208.68   119.85     293
12       0        20        30       5  ...    713   173.71   209.39     447
13       0        20        30       5  ...    594   152.28   162.15     372
14      60        20        30       5  ...    504   174.84   148.05     316
15       0        20        30       5  ...    634   235.75   155.10     397
16      60        20         6       5  ...    522   197.40   126.90     327
17      90        20        30       5  ...    684   197.40   112.80     429
18      90        20        30       5  ...    468   186.12   155.10     293
19      60        20         0       5  ...    522   208.68   141.00     327
20       0        20        30       5  ...    432   169.20   126.90     271
21      60        20        30       5  ...    653   241.96   116.33     409
22      60        20        30       5  ...    594   223.34   155.10     372
23      60        20         0       5  ...    693   173.71   155.10     434
24      90        20        30       5  ...    468   180.48   133.95     293
25      90        20        30       5  ...    468   191.76   119.85     293
26      90        20        30       5  ...    455   217.14   131.84     285
27       0        20        30       5  ...    673   179.92   155.10     422
28       0        20        30       5  ...    614   198.53   147.34     385
29      60        20        30       5  ...    634   192.32   193.87     397
30      60        20         0       5  ...    634   223.34   116.33     397
31       0        20        30       5  ...    540   157.92   176.25     338
32      60        20        30       5  ...    752   148.90   193.87     472

    atk_20  def_20  hp_20   atk_1  def_1  hp_1
0   135.72  152.10    281   69.60   78.0   144
1   145.08  105.30    234   74.40   54.0   120
2   200.77  115.83    278  102.96   59.4   143
3   164.74  135.14    299   84.48   69.3   153
4   180.18  128.70    288   92.40   66.0   148
5   169.88  122.26    278   87.12   62.7   143
6   159.12   87.75    318   81.60   45.0   163
7   135.72  122.85    271   69.60   63.0   139
8   154.44  105.30    253   79.20   54.0   130
9   154.44  141.57    329   79.20   72.6   169
10  169.88   96.53    247   87.12   49.5   127
11  173.16   99.45    243   88.80   51.0   125
12  144.14  173.75    371   73.92   89.1   190
13  126.36  134.55    309   64.80   69.0   158
14  145.08  122.85    262   74.40   63.0   134
15  195.62  128.70    329  100.32   66.0   169
16  163.80  105.30    271   84.00   54.0   139
17  163.80   93.60    356   84.00   48.0   182
18  154.44  128.70    243   79.20   66.0   125
19  173.16  117.00    271   88.80   60.0   139
20  140.40  105.30    225   72.00   54.0   115
21  200.77   96.53    340  102.96   49.5   174
22  185.33  128.70    309   95.04   66.0   158
23  144.14  128.70    360   73.92   66.0   185
24  149.76  111.15    243   76.80   57.0   125
25  159.12   99.45    243   81.60   51.0   125
26  180.18  109.40    237   92.40   56.1   121
27  149.29  128.70    350   76.56   66.0   180
28  164.74  122.26    319   84.48   62.7   164
29  159.59  160.87    329   81.84   82.5   169
30  185.33   96.53    329   95.04   49.5   169
31  131.04  146.25    281   67.20   75.0   144
32  123.55  160.87    391   63.36   82.5   201

[33 rows x 51 columns]>

Dataset Statistical Information

In [24]:
hsr_df.describe()

,rarity,wb_b-atk,wb_skill,wb_ult,er_b-atk,er_skill,er_ult,spd,crit-r,crit-d,...,hp_40,atk_20a,def_20a,hp_20a,atk_20,def_20,hp_20,atk_1,def_1,hp_1
count,33.000000,33.0,33.000000,33.000000,33.0,33.000000,33.0,33.000000,3.300000e+01,33.0,...,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000
mean,4.515152,30.0,30.909091,50.909091,20.0,25.212121,5.0,101.545455,5.000000e-02,0.5,...,564.727273,192.922121,146.512121,353.848485,160.083939,121.573939,293.545455,82.094545,62.345455,150.606061
std,0.507519,0.0,27.541291,33.945143,0.0,10.451548,0.0,5.551413,2.113944e-17,0.0,...,86.543079,24.688932,25.715125,54.301313,20.486640,21.337956,44.986172,10.505988,10.942923,23.081296
min,4.000000,30.0,0.000000,0.000000,20.0,0.000000,5.0,90.000000,5.000000e-02,0.5,...,432.000000,148.900000,105.750000,271.000000,123.550000,87.750000,225.000000,63.360000,45.000000,115.000000
25%,4.000000,30.0,0.000000,0.000000,20.0,30.000000,5.0,98.000000,5.000000e-02,0.5,...,486.000000,174.840000,126.900000,305.000000,145.080000,105.300000,253.000000,74.400000,54.000000,130.000000
50%,5.000000,30.0,30.000000,60.000000,20.0,30.000000,5.0,101.000000,5.000000e-02,0.5,...,540.000000,191.760000,147.340000,338.000000,159.120000,122.260000,281.000000,81.600000,62.700000,144.000000
75%,5.000000,30.0,60.000000,60.000000,20.0,30.000000,5.0,105.000000,5.000000e-02,0.5,...,634.000000,208.680000,155.100000,397.000000,173.160000,128.700000,329.000000,88.800000,66.000000,169.000000
max,5.000000,30.0,60.000000,90.000000,20.0,30.000000,5.0,115.000000,5.000000e-02,0.5,...,752.000000,241.960000,209.390000,472.000000,200.770000,173.750000,391.000000,102.960000,89.100000,201.000000

Number of rows and columns of dataset: 33, 51

In [19]:
hsr_df.shape

(33, 51)

Number of characters as of version 1.3

In [20]:
num_char = 33

print('There are {} characters in the dataset.zx'.format(num_char))

There are 33 characters in the dataset

Number of unique paths of characters

In [26]:
hsr_df.path.unique()

array(['preservation', 'hunt', 'erudition', 'nihility', 'destruction',
       'harmony', 'abundance'], dtype=object)

Number of unique elements of characters

In [27]:
hsr_df.combat_type.unique()

array(['ice', 'wind', 'fire', 'imaginary', 'lightning', 'quantum',
       'physical'], dtype=object)

Character with ID at 21

In [32]:
hsr_df.character[21]

'luocha'

Character with ID at 13

In [33]:
hsr_df.at[13, 'character']

'natasha'

Dataframe containing 4 star characters

In [42]:
hsr_df_4star = hsr_df[hsr_df.rarity == 4]

hsr_df_4star

,character,rarity,path,combat_type,wb_b-atk,wb_skill,wb_ult,er_b-atk,er_skill,er_ult,...,hp_40,atk_20a,def_20a,hp_20a,atk_20,def_20,hp_20,atk_1,def_1,hp_1
0,march_7th,4,preservation,ice,30,0,60,20,30,5,...,540,163.56,183.30,338,135.72,152.10,281,69.6,78.0,144
1,dan_heng,4,hunt,wind,30,60,90,20,30,5,...,450,174.84,126.90,282,145.08,105.30,234,74.4,54.0,120
6,arlan,4,destruction,lightning,30,60,60,20,30,5,...,612,191.76,105.75,384,159.12,87.75,318,81.6,45.0,163
7,asta,4,harmony,fire,30,30,0,20,6,5,...,522,163.56,148.05,327,135.72,122.85,271,69.6,63.0,139
8,herta,4,erudition,ice,30,30,60,20,30,5,...,486,186.12,126.90,305,154.44,105.30,253,79.2,54.0,130
11,serval,4,erudition,lightning,30,60,60,20,30,5,...,468,208.68,119.85,293,173.16,99.45,243,88.8,51.0,125
13,natasha,4,abundance,physical,30,0,0,20,30,5,...,594,152.28,162.15,372,126.36,134.55,309,64.8,69.0,158
14,pela,4,nihility,ice,30,60,60,20,30,5,...,504,174.84,148.05,316,145.08,122.85,262,74.4,63.0,134
16,sampo,4,nihility,wind,30,30,60,20,6,5,...,522,197.40,126.90,327,163.80,105.30,271,84.0,54.0,139
17,hook,4,destruction,fire,30,60,90,20,30,5,...,684,197.40,112.80,429,163.80,93.60,356,84.0,48.0,182
18,luka,4,nihility,physical,30,60,90,20,30,5,...,468,186.12,155.10,293,154.44,128.70,243,79.2,66.0,125
19,qingque,4,erudition,quantum,30,0,60,20,0,5,...,522,208.68,141.00,327,173.16,117.00,271,88.8,60.0,139
20,tingyun,4,harmony,lightning,30,0,0,20,30,5,...,432,169.20,126.90,271,140.40,105.30,225,72.0,54.0,115
24,sushang,4,hunt,physical,30,60,90,20,30,5,...,468,180.48,133.95,293,149.76,111.15,243,76.8,57.0,125
25,yukong,4,harmony,imaginary,30,0,90,20,30,5,...,468,191.76,119.85,293,159.12,99.45,243,81.6,51.0,125
31,lynx,4,abundance,quantum,30,0,0,20,30,5,...,540,157.92,176.25,338,131.04,146.25,281,67.2,75.0,144

Dataframe containing 5 star characters

In [43]:
hsr_df_5star = hsr_df[hsr_df.rarity == 5]

hsr_df_5star

,character,rarity,path,combat_type,wb_b-atk,wb_skill,wb_ult,er_b-atk,er_skill,er_ult,...,hp_40,atk_20a,def_20a,hp_20a,atk_20,def_20,hp_20,atk_1,def_1,hp_1
2,himeko,5,erudition,fire,30,60,60,20,10,5,...,535,241.96,139.59,335,200.77,115.83,278,102.96,59.4,143
3,welt,5,nihility,imaginary,30,30,60,20,30,5,...,574,198.53,162.86,360,164.74,135.14,299,84.48,69.3,153
4,kafka,5,nihility,lightning,30,60,60,20,30,5,...,554,217.14,155.10,347,180.18,128.70,288,92.40,66.0,148
5,silver_wolf,5,nihility,quantum,30,60,90,20,30,5,...,535,204.73,147.34,335,169.88,122.26,278,87.12,62.7,143
9,bronya,5,harmony,wind,30,0,0,20,30,5,...,634,186.12,170.61,397,154.44,141.57,329,79.20,72.6,169
10,seele,5,hunt,quantum,30,60,90,20,30,5,...,475,204.73,116.33,298,169.88,96.53,247,87.12,49.5,127
12,gepard,5,preservation,ice,30,60,0,20,30,5,...,713,173.71,209.39,447,144.14,173.75,371,73.92,89.1,190
15,clara,5,destruction,physical,30,30,0,20,30,5,...,634,235.75,155.10,397,195.62,128.70,329,100.32,66.0,169
21,luocha,5,abundance,imaginary,30,0,60,20,30,5,...,653,241.96,116.33,409,200.77,96.53,340,102.96,49.5,174
22,jing_yuan,5,erudition,lightning,30,30,60,20,30,5,...,594,223.34,155.10,372,185.33,128.70,309,95.04,66.0,158
23,blade,5,destruction,wind,30,0,60,20,0,5,...,693,173.71,155.10,434,144.14,128.70,360,73.92,66.0,185
26,yanqing,5,hunt,ice,30,60,90,20,30,5,...,455,217.14,131.84,285,180.18,109.40,237,92.40,56.1,121
27,bailu,5,abundance,lightning,30,0,0,20,30,5,...,673,179.92,155.10,422,149.29,128.70,350,76.56,66.0,180
28,trailblazer_0,5,destruction,physical,30,60,0,20,30,5,...,614,198.53,147.34,385,164.74,122.26,319,84.48,62.7,164
29,trailblazer_1,5,preservation,fire,30,0,60,20,30,5,...,634,192.32,193.87,397,159.59,160.87,329,81.84,82.5,169
30,dan_heng_IL,5,destruction,imaginary,30,0,60,20,0,5,...,634,223.34,116.33,397,185.33,96.53,329,95.04,49.5,169
32,fu_xuan,5,preservation,quantum,30,0,60,20,30,5,...,752,148.90,193.87,472,123.55,160.87,391,63.36,82.5,201

4 star character ratio over total number of characters

In [47]:
rarity_4star_ratio = hsr_df_4star['character'].count() / hsr_df['character'].count()

rarity_4star_ratio

0.48484848484848486

Top 10 4 star characters with the highest base attack value at level 80

In [51]:
hsr_df_4star[['character','atk_80']].sort_values('atk_80', ascending=False).head(10)

   character  atk_80
11    serval  652.68
19   qingque  652.68
16     sampo  617.40
17      hook  617.40
6      arlan  599.76
25    yukong  599.76
8      herta  582.12
18      luka  582.12
24   sushang  564.48
1   dan_heng  546.84

Top 10 5 star characters with the highest base attack value at level 80

In [52]:
hsr_df_5star[['character','atk_80']].sort_values('atk_80', ascending=False).head(10)

      character  atk_80
2        himeko  756.76
21       luocha  756.76
15        clara  737.35
22    jing_yuan  698.54
30  dan_heng_IL  698.54
4         kafka  679.14
26      yanqing  679.14
5   silver_wolf  640.33
10        seele  640.33
3          welt  620.93

Top 10 characters with the lowest base defense value at level 80

In [67]:
hsr_df[['character','def_80']].sort_values('def_80', ascending=True).head(10)

      character  def_80
6         arlan  330.75
17         hook  352.80
21       luocha  363.83
10        seele  363.83
30  dan_heng_IL  363.83
25       yukong  374.85
11       serval  374.85
16        sampo  396.90
1      dan_heng  396.90
8         herta  396.90

Segregation of characters based on defense value at level 80 by percentiles

In [82]:
q25, q50, q75, q100 = hsr_df['def_80'].quantile([0.25, 0.5, 0.75, 1])

hsr_df_sorted_def80 = hsr_df.sort_values('def_80', ascending=False)

hsr_df_def80_25 = hsr_df_sorted_def80[['character','def_80','path']][hsr_df['def_80'] <= q25]
hsr_df_def80_50 = hsr_df_sorted_def80[['character','def_80','path']][(hsr_df['def_80'] > q25) & (hsr_df['def_80'] <= q50)]
hsr_df_def80_75 = hsr_df_sorted_def80[['character','def_80','path']][(hsr_df['def_80'] > q50) & (hsr_df['def_80'] <= q75)]
hsr_df_def80_100 = hsr_df_sorted_def80[['character','def_80','path']][hsr_df['def_80'] > q75]

print("25th percentile data:\n", hsr_df_def80_25)
print("50th percentile data:\n", hsr_df_def80_50)
print("75th percentile data:\n", hsr_df_def80_75)
print("100th percentile data:\n", hsr_df_def80_100)

25th percentile data:
       character  def_80         path
8         herta  396.90    erudition
20      tingyun  396.90      harmony
1      dan_heng  396.90         hunt
16        sampo  396.90     nihility
11       serval  374.85    erudition
25       yukong  374.85      harmony
10        seele  363.83         hunt
21       luocha  363.83    abundance
30  dan_heng_IL  363.83  destruction
17         hook  352.80  destruction
6         arlan  330.75  destruction
50th percentile data:
         character  def_80         path
28  trailblazer_0  460.84  destruction
5     silver_wolf  460.84     nihility
19        qingque  441.00    erudition
2          himeko  436.59    erudition
24        sushang  418.95         hunt
26        yanqing  412.34         hunt
75th percentile data:
     character  def_80         path
4       kafka  485.10     nihility
27      bailu  485.10    abundance
23      blade  485.10  destruction
22  jing_yuan  485.10    erudition
15      clara  485.10  destruction
18       luka  485.10     nihility
14       pela  463.05     nihility
7        asta  463.05      harmony
100th percentile data:
         character  def_80          path
12         gepard  654.89  preservation
32        fu_xuan  606.37  preservation
29  trailblazer_1  606.37  preservation
0       march_7th  573.30  preservation
31           lynx  551.25     abundance
9          bronya  533.61       harmony
3            welt  509.36      nihility
13        natasha  507.15     abundance

<ipython-input-82-18798a6d4020>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hsr_df_def80_25 = hsr_df_sorted_def80[['character','def_80','path']][hsr_df['def_80'] <= q25]
<ipython-input-82-18798a6d4020>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hsr_df_def80_50 = hsr_df_sorted_def80[['character','def_80','path']][(hsr_df['def_80'] > q25) & (hsr_df['def_80'] <= q50)]
<ipython-input-82-18798a6d4020>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hsr_df_def80_75 = hsr_df_sorted_def80[['character','def_80','path']][(hsr_df['def_80'] > q50) & (hsr_df['def_80'] <= q75)]
<ipython-input-82-18798a6d4020>:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hsr_df_def80_100 = hsr_df_sorted_def80[['character','def_80','path']][hsr_df['def_80'] > q75]

Define assign_score function to assign values 1 to 4 based on percentile.

In [83]:
def assign_score(value):
    if value <= q25:
        return 1
    elif value <= q50:
        return 2
    elif value <= q75:
        return 3
    else:
        return 4

Apply assign_score function to add new defense score column to original dataframe.

In [84]:
hsr_df['def_score'] = hsr_df['def_80'].apply(assign_score)

hsr_df

,character,rarity,path,combat_type,wb_b-atk,wb_skill,wb_ult,er_b-atk,er_skill,er_ult,...,hp_20a,atk_20,def_20,hp_20,atk_1,def_1,hp_1,defense_score,hp_score,def_score
0,march_7th,4,preservation,ice,30,0,60,20,30,5,...,338,135.72,152.10,281,69.60,78.0,144,4,2,4
1,dan_heng,4,hunt,wind,30,60,90,20,30,5,...,282,145.08,105.30,234,74.40,54.0,120,1,1,1
2,himeko,5,erudition,fire,30,60,60,20,10,5,...,335,200.77,115.83,278,102.96,59.4,143,2,2,2
3,welt,5,nihility,imaginary,30,30,60,20,30,5,...,360,164.74,135.14,299,84.48,69.3,153,4,3,4
4,kafka,5,nihility,lightning,30,60,60,20,30,5,...,347,180.18,128.70,288,92.40,66.0,148,3,3,3
5,silver_wolf,5,nihility,quantum,30,60,90,20,30,5,...,335,169.88,122.26,278,87.12,62.7,143,2,2,2
6,arlan,4,destruction,lightning,30,60,60,20,30,5,...,384,159.12,87.75,318,81.60,45.0,163,1,3,1
7,asta,4,harmony,fire,30,30,0,20,6,5,...,327,135.72,122.85,271,69.60,63.0,139,3,2,3
8,herta,4,erudition,ice,30,30,60,20,30,5,...,305,154.44,105.30,253,79.20,54.0,130,1,1,1
9,bronya,5,harmony,wind,30,0,0,20,30,5,...,397,154.44,141.57,329,79.20,72.6,169,4,3,4
10,seele,5,hunt,quantum,30,60,90,20,30,5,...,298,169.88,96.53,247,87.12,49.5,127,1,1,1
11,serval,4,erudition,lightning,30,60,60,20,30,5,...,293,173.16,99.45,243,88.80,51.0,125,1,1,1
12,gepard,5,preservation,ice,30,60,0,20,30,5,...,447,144.14,173.75,371,73.92,89.1,190,4,4,4
13,natasha,4,abundance,physical,30,0,0,20,30,5,...,372,126.36,134.55,309,64.80,69.0,158,4,3,4
14,pela,4,nihility,ice,30,60,60,20,30,5,...,316,145.08,122.85,262,74.40,63.0,134,3,2,3
15,clara,5,destruction,physical,30,30,0,20,30,5,...,397,195.62,128.70,329,100.32,66.0,169,3,3,3
16,sampo,4,nihility,wind,30,30,60,20,6,5,...,327,163.80,105.30,271,84.00,54.0,139,1,2,1
17,hook,4,destruction,fire,30,60,90,20,30,5,...,429,163.80,93.60,356,84.00,48.0,182,1,4,1
18,luka,4,nihility,physical,30,60,90,20,30,5,...,293,154.44,128.70,243,79.20,66.0,125,3,1,3
19,qingque,4,erudition,quantum,30,0,60,20,0,5,...,327,173.16,117.00,271,88.80,60.0,139,2,2,2
20,tingyun,4,harmony,lightning,30,0,0,20,30,5,...,271,140.40,105.30,225,72.00,54.0,115,1,1,1
21,luocha,5,abundance,imaginary,30,0,60,20,30,5,...,409,200.77,96.53,340,102.96,49.5,174,1,4,1
22,jing_yuan,5,erudition,lightning,30,30,60,20,30,5,...,372,185.33,128.70,309,95.04,66.0,158,3,3,3
23,blade,5,destruction,wind,30,0,60,20,0,5,...,434,144.14,128.70,360,73.92,66.0,185,3,4,3
24,sushang,4,hunt,physical,30,60,90,20,30,5,...,293,149.76,111.15,243,76.80,57.0,125,2,1,2
25,yukong,4,harmony,imaginary,30,0,90,20,30,5,...,293,159.12,99.45,243,81.60,51.0,125,1,1,1
26,yanqing,5,hunt,ice,30,60,90,20,30,5,...,285,180.18,109.40,237,92.40,56.1,121,2,1,2
27,bailu,5,abundance,lightning,30,0,0,20,30,5,...,422,149.29,128.70,350,76.56,66.0,180,3,4,3
28,trailblazer_0,5,destruction,physical,30,60,0,20,30,5,...,385,164.74,122.26,319,84.48,62.7,164,2,3,2
29,trailblazer_1,5,preservation,fire,30,0,60,20,30,5,...,397,159.59,160.87,329,81.84,82.5,169,4,3,4
30,dan_heng_IL,5,destruction,imaginary,30,0,60,20,0,5,...,397,185.33,96.53,329,95.04,49.5,169,1,3,1
31,lynx,4,abundance,quantum,30,0,0,20,30,5,...,338,131.04,146.25,281,67.20,75.0,144,4,2,4
32,fu_xuan,5,preservation,quantum,30,0,60,20,30,5,...,472,123.55,160.87,391,63.36,82.5,201,4,4,4

Segregation done similar for hp value at level 80

In [85]:
q25, q50, q75, q100 = hsr_df['hp_80'].quantile([0.25, 0.5, 0.75, 1])

hsr_df_sorted_hp80 = hsr_df.sort_values('hp_80', ascending=False)

hsr_df_hp80_25 = hsr_df_sorted_hp80[['character','hp_80','path']][hsr_df['hp_80'] <= q25]
hsr_df_hp80_50 = hsr_df_sorted_hp80[['character','hp_80','path']][(hsr_df['hp_80'] > q25) & (hsr_df['hp_80'] <= q50)]
hsr_df_hp80_75 = hsr_df_sorted_hp80[['character','hp_80','path']][(hsr_df['hp_80'] > q50) & (hsr_df['hp_80'] <= q75)]
hsr_df_hp80_100 = hsr_df_sorted_hp80[['character','hp_80','path']][hsr_df['hp_80'] > q75]

print("25th percentile data:\n", hsr_df_hp80_25)
print("50th percentile data:\n", hsr_df_hp80_50)
print("75th percentile data:\n", hsr_df_hp80_75)
print("100th percentile data:\n", hsr_df_hp80_100)

25th percentile data:
    character   hp_80       path
8      herta  953.00  erudition
10     seele  931.00       hunt
18      luka  917.28   nihility
11    serval  917.00  erudition
24   sushang  917.00       hunt
25    yukong  917.00    harmony
26   yanqing  893.00       hunt
1   dan_heng  882.00       hunt
20   tingyun  847.00    harmony
50th percentile data:
       character    hp_80          path
31         lynx  1058.00     abundance
0     march_7th  1058.00  preservation
2        himeko  1048.00     erudition
5   silver_wolf  1047.82      nihility
19      qingque  1023.00     erudition
7          asta  1023.00       harmony
16        sampo  1023.00      nihility
14         pela   988.00      nihility
75th percentile data:
         character    hp_80          path
29  trailblazer_1  1242.00  preservation
30    dan_heng_IL  1242.00   destruction
9          bronya  1242.00       harmony
15          clara  1242.00   destruction
28  trailblazer_0  1203.00   destruction
6           arlan  1199.52   destruction
13        natasha  1164.00     abundance
22      jing_yuan  1164.00     erudition
3            welt  1125.43      nihility
4           kafka  1086.62      nihility
100th percentile data:
    character   hp_80          path
32   fu_xuan  1475.0  preservation
12    gepard  1397.0  preservation
23     blade  1358.0   destruction
17      hook  1341.0   destruction
27     bailu  1319.0     abundance
21    luocha  1281.0     abundance

<ipython-input-85-eba2fa28b8db>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hsr_df_hp80_25 = hsr_df_sorted_hp80[['character','hp_80','path']][hsr_df['hp_80'] <= q25]
<ipython-input-85-eba2fa28b8db>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hsr_df_hp80_50 = hsr_df_sorted_hp80[['character','hp_80','path']][(hsr_df['hp_80'] > q25) & (hsr_df['hp_80'] <= q50)]
<ipython-input-85-eba2fa28b8db>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hsr_df_hp80_75 = hsr_df_sorted_hp80[['character','hp_80','path']][(hsr_df['hp_80'] > q50) & (hsr_df['hp_80'] <= q75)]
<ipython-input-85-eba2fa28b8db>:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hsr_df_hp80_100 = hsr_df_sorted_hp80[['character','hp_80','path']][hsr_df['hp_80'] > q75]

Assign score function used to create hp score column on original dataframe.

In [89]:
hsr_df['hp_score'] = hsr_df['hp_80'].apply(assign_score)

hsr_df

,character,rarity,path,combat_type,wb_b-atk,wb_skill,wb_ult,er_b-atk,er_skill,er_ult,...,def_20a,hp_20a,atk_20,def_20,hp_20,atk_1,def_1,hp_1,hp_score,def_score
0,march_7th,4,preservation,ice,30,0,60,20,30,5,...,183.30,338,135.72,152.10,281,69.60,78.0,144,2,4
1,dan_heng,4,hunt,wind,30,60,90,20,30,5,...,126.90,282,145.08,105.30,234,74.40,54.0,120,1,1
2,himeko,5,erudition,fire,30,60,60,20,10,5,...,139.59,335,200.77,115.83,278,102.96,59.4,143,2,2
3,welt,5,nihility,imaginary,30,30,60,20,30,5,...,162.86,360,164.74,135.14,299,84.48,69.3,153,3,4
4,kafka,5,nihility,lightning,30,60,60,20,30,5,...,155.10,347,180.18,128.70,288,92.40,66.0,148,3,3
5,silver_wolf,5,nihility,quantum,30,60,90,20,30,5,...,147.34,335,169.88,122.26,278,87.12,62.7,143,2,2
6,arlan,4,destruction,lightning,30,60,60,20,30,5,...,105.75,384,159.12,87.75,318,81.60,45.0,163,3,1
7,asta,4,harmony,fire,30,30,0,20,6,5,...,148.05,327,135.72,122.85,271,69.60,63.0,139,2,3
8,herta,4,erudition,ice,30,30,60,20,30,5,...,126.90,305,154.44,105.30,253,79.20,54.0,130,1,1
9,bronya,5,harmony,wind,30,0,0,20,30,5,...,170.61,397,154.44,141.57,329,79.20,72.6,169,3,4
10,seele,5,hunt,quantum,30,60,90,20,30,5,...,116.33,298,169.88,96.53,247,87.12,49.5,127,1,1
11,serval,4,erudition,lightning,30,60,60,20,30,5,...,119.85,293,173.16,99.45,243,88.80,51.0,125,1,1
12,gepard,5,preservation,ice,30,60,0,20,30,5,...,209.39,447,144.14,173.75,371,73.92,89.1,190,4,4
13,natasha,4,abundance,physical,30,0,0,20,30,5,...,162.15,372,126.36,134.55,309,64.80,69.0,158,3,4
14,pela,4,nihility,ice,30,60,60,20,30,5,...,148.05,316,145.08,122.85,262,74.40,63.0,134,2,3
15,clara,5,destruction,physical,30,30,0,20,30,5,...,155.10,397,195.62,128.70,329,100.32,66.0,169,3,3
16,sampo,4,nihility,wind,30,30,60,20,6,5,...,126.90,327,163.80,105.30,271,84.00,54.0,139,2,1
17,hook,4,destruction,fire,30,60,90,20,30,5,...,112.80,429,163.80,93.60,356,84.00,48.0,182,4,1
18,luka,4,nihility,physical,30,60,90,20,30,5,...,155.10,293,154.44,128.70,243,79.20,66.0,125,1,3
19,qingque,4,erudition,quantum,30,0,60,20,0,5,...,141.00,327,173.16,117.00,271,88.80,60.0,139,2,2
20,tingyun,4,harmony,lightning,30,0,0,20,30,5,...,126.90,271,140.40,105.30,225,72.00,54.0,115,1,1
21,luocha,5,abundance,imaginary,30,0,60,20,30,5,...,116.33,409,200.77,96.53,340,102.96,49.5,174,4,1
22,jing_yuan,5,erudition,lightning,30,30,60,20,30,5,...,155.10,372,185.33,128.70,309,95.04,66.0,158,3,3
23,blade,5,destruction,wind,30,0,60,20,0,5,...,155.10,434,144.14,128.70,360,73.92,66.0,185,4,3
24,sushang,4,hunt,physical,30,60,90,20,30,5,...,133.95,293,149.76,111.15,243,76.80,57.0,125,1,2
25,yukong,4,harmony,imaginary,30,0,90,20,30,5,...,119.85,293,159.12,99.45,243,81.60,51.0,125,1,1
26,yanqing,5,hunt,ice,30,60,90,20,30,5,...,131.84,285,180.18,109.40,237,92.40,56.1,121,1,2
27,bailu,5,abundance,lightning,30,0,0,20,30,5,...,155.10,422,149.29,128.70,350,76.56,66.0,180,4,3
28,trailblazer_0,5,destruction,physical,30,60,0,20,30,5,...,147.34,385,164.74,122.26,319,84.48,62.7,164,3,2
29,trailblazer_1,5,preservation,fire,30,0,60,20,30,5,...,193.87,397,159.59,160.87,329,81.84,82.5,169,3,4
30,dan_heng_IL,5,destruction,imaginary,30,0,60,20,0,5,...,116.33,397,185.33,96.53,329,95.04,49.5,169,3,1
31,lynx,4,abundance,quantum,30,0,0,20,30,5,...,176.25,338,131.04,146.25,281,67.20,75.0,144,2,4
32,fu_xuan,5,preservation,quantum,30,0,60,20,30,5,...,193.87,472,123.55,160.87,391,63.36,82.5,201,4,4

Display characters that have value 4 for both def_score and hp_score, implying that they are more "tanky".

In [90]:
hsr_df[(hsr_df['def_score'] == 4) & (hsr_df['hp_score'] == 4)]

,character,rarity,path,combat_type,wb_b-atk,wb_skill,wb_ult,er_b-atk,er_skill,er_ult,...,def_20a,hp_20a,atk_20,def_20,hp_20,atk_1,def_1,hp_1,hp_score,def_score
12,gepard,5,preservation,ice,30,60,0,20,30,5,...,209.39,447,144.14,173.75,371,73.92,89.1,190,4,4
32,fu_xuan,5,preservation,quantum,30,0,60,20,30,5,...,193.87,472,123.55,160.87,391,63.36,82.5,201,4,4

In [97]:
hsr_tankiness_df = hsr_df.sort_values(['def_score','hp_score'], ascending=False)

hsr_tankiness_df

,character,rarity,path,combat_type,wb_b-atk,wb_skill,wb_ult,er_b-atk,er_skill,er_ult,...,def_20a,hp_20a,atk_20,def_20,hp_20,atk_1,def_1,hp_1,hp_score,def_score
12,gepard,5,preservation,ice,30,60,0,20,30,5,...,209.39,447,144.14,173.75,371,73.92,89.1,190,4,4
32,fu_xuan,5,preservation,quantum,30,0,60,20,30,5,...,193.87,472,123.55,160.87,391,63.36,82.5,201,4,4
3,welt,5,nihility,imaginary,30,30,60,20,30,5,...,162.86,360,164.74,135.14,299,84.48,69.3,153,3,4
9,bronya,5,harmony,wind,30,0,0,20,30,5,...,170.61,397,154.44,141.57,329,79.20,72.6,169,3,4
13,natasha,4,abundance,physical,30,0,0,20,30,5,...,162.15,372,126.36,134.55,309,64.80,69.0,158,3,4
29,trailblazer_1,5,preservation,fire,30,0,60,20,30,5,...,193.87,397,159.59,160.87,329,81.84,82.5,169,3,4
0,march_7th,4,preservation,ice,30,0,60,20,30,5,...,183.30,338,135.72,152.10,281,69.60,78.0,144,2,4
31,lynx,4,abundance,quantum,30,0,0,20,30,5,...,176.25,338,131.04,146.25,281,67.20,75.0,144,2,4
23,blade,5,destruction,wind,30,0,60,20,0,5,...,155.10,434,144.14,128.70,360,73.92,66.0,185,4,3
27,bailu,5,abundance,lightning,30,0,0,20,30,5,...,155.10,422,149.29,128.70,350,76.56,66.0,180,4,3
4,kafka,5,nihility,lightning,30,60,60,20,30,5,...,155.10,347,180.18,128.70,288,92.40,66.0,148,3,3
15,clara,5,destruction,physical,30,30,0,20,30,5,...,155.10,397,195.62,128.70,329,100.32,66.0,169,3,3
22,jing_yuan,5,erudition,lightning,30,30,60,20,30,5,...,155.10,372,185.33,128.70,309,95.04,66.0,158,3,3
7,asta,4,harmony,fire,30,30,0,20,6,5,...,148.05,327,135.72,122.85,271,69.60,63.0,139,2,3
14,pela,4,nihility,ice,30,60,60,20,30,5,...,148.05,316,145.08,122.85,262,74.40,63.0,134,2,3
18,luka,4,nihility,physical,30,60,90,20,30,5,...,155.10,293,154.44,128.70,243,79.20,66.0,125,1,3
28,trailblazer_0,5,destruction,physical,30,60,0,20,30,5,...,147.34,385,164.74,122.26,319,84.48,62.7,164,3,2
2,himeko,5,erudition,fire,30,60,60,20,10,5,...,139.59,335,200.77,115.83,278,102.96,59.4,143,2,2
5,silver_wolf,5,nihility,quantum,30,60,90,20,30,5,...,147.34,335,169.88,122.26,278,87.12,62.7,143,2,2
19,qingque,4,erudition,quantum,30,0,60,20,0,5,...,141.00,327,173.16,117.00,271,88.80,60.0,139,2,2
24,sushang,4,hunt,physical,30,60,90,20,30,5,...,133.95,293,149.76,111.15,243,76.80,57.0,125,1,2
26,yanqing,5,hunt,ice,30,60,90,20,30,5,...,131.84,285,180.18,109.40,237,92.40,56.1,121,1,2
17,hook,4,destruction,fire,30,60,90,20,30,5,...,112.80,429,163.80,93.60,356,84.00,48.0,182,4,1
21,luocha,5,abundance,imaginary,30,0,60,20,30,5,...,116.33,409,200.77,96.53,340,102.96,49.5,174,4,1
6,arlan,4,destruction,lightning,30,60,60,20,30,5,...,105.75,384,159.12,87.75,318,81.60,45.0,163,3,1
30,dan_heng_IL,5,destruction,imaginary,30,0,60,20,0,5,...,116.33,397,185.33,96.53,329,95.04,49.5,169,3,1
16,sampo,4,nihility,wind,30,30,60,20,6,5,...,126.90,327,163.80,105.30,271,84.00,54.0,139,2,1
1,dan_heng,4,hunt,wind,30,60,90,20,30,5,...,126.90,282,145.08,105.30,234,74.40,54.0,120,1,1
8,herta,4,erudition,ice,30,30,60,20,30,5,...,126.90,305,154.44,105.30,253,79.20,54.0,130,1,1
10,seele,5,hunt,quantum,30,60,90,20,30,5,...,116.33,298,169.88,96.53,247,87.12,49.5,127,1,1
11,serval,4,erudition,lightning,30,60,60,20,30,5,...,119.85,293,173.16,99.45,243,88.80,51.0,125,1,1
20,tingyun,4,harmony,lightning,30,0,0,20,30,5,...,126.90,271,140.40,105.30,225,72.00,54.0,115,1,1
25,yukong,4,harmony,imaginary,30,0,90,20,30,5,...,119.85,293,159.12,99.45,243,81.60,51.0,125,1,1

Write results back into CSV file

In [98]:
hsr_tankiness_df = hsr_tankiness_df[[
    'character',
    'rarity',
    'path',
    'combat_type',
    'atk_80',
    'def_80',
    'hp_80',
    'def_score',
    'hp_score'
]]

In [99]:
hsr_tankiness_df

,character,rarity,path,combat_type,atk_80,def_80,hp_80,def_score,hp_score
12,gepard,5,preservation,ice,543.31,654.89,1397.00,4,4
32,fu_xuan,5,preservation,quantum,465.70,606.37,1475.00,4,4
3,welt,5,nihility,imaginary,620.93,509.36,1125.43,4,3
9,bronya,5,harmony,wind,582.12,533.61,1242.00,4,3
13,natasha,4,abundance,physical,476.28,507.15,1164.00,4,3
29,trailblazer_1,5,preservation,fire,601.52,606.37,1242.00,4,3
0,march_7th,4,preservation,ice,511.56,573.30,1058.00,4,2
31,lynx,4,abundance,quantum,493.92,551.25,1058.00,4,2
23,blade,5,destruction,wind,543.31,485.10,1358.00,3,4
27,bailu,5,abundance,lightning,562.72,485.10,1319.00,3,4
4,kafka,5,nihility,lightning,679.14,485.10,1086.62,3,3
15,clara,5,destruction,physical,737.35,485.10,1242.00,3,3
22,jing_yuan,5,erudition,lightning,698.54,485.10,1164.00,3,3
7,asta,4,harmony,fire,511.56,463.05,1023.00,3,2
14,pela,4,nihility,ice,546.84,463.05,988.00,3,2
18,luka,4,nihility,physical,582.12,485.10,917.28,3,1
28,trailblazer_0,5,destruction,physical,620.93,460.84,1203.00,2,3
2,himeko,5,erudition,fire,756.76,436.59,1048.00,2,2
5,silver_wolf,5,nihility,quantum,640.33,460.84,1047.82,2,2
19,qingque,4,erudition,quantum,652.68,441.00,1023.00,2,2
24,sushang,4,hunt,physical,564.48,418.95,917.00,2,1
26,yanqing,5,hunt,ice,679.14,412.34,893.00,2,1
17,hook,4,destruction,fire,617.40,352.80,1341.00,1,4
21,luocha,5,abundance,imaginary,756.76,363.83,1281.00,1,4
6,arlan,4,destruction,lightning,599.76,330.75,1199.52,1,3
30,dan_heng_IL,5,destruction,imaginary,698.54,363.83,1242.00,1,3
16,sampo,4,nihility,wind,617.40,396.90,1023.00,1,2
1,dan_heng,4,hunt,wind,546.84,396.90,882.00,1,1
8,herta,4,erudition,ice,582.12,396.90,953.00,1,1
10,seele,5,hunt,quantum,640.33,363.83,931.00,1,1
11,serval,4,erudition,lightning,652.68,374.85,917.00,1,1
20,tingyun,4,harmony,lightning,529.20,396.90,847.00,1,1
25,yukong,4,harmony,imaginary,599.76,374.85,917.00,1,1

In [96]:
hsr_tankiness_df.to_csv('hsr_char_tankiness_v1.3.csv', index=None)